### ISSUE TITLE
Issue on last ver.

### ISSUE THREAD

**Issue by Hollicsh** [BloodDragon2580/FastItemLevel#1]
98x FastItemLevel/FastItemLevel.lua:261: bad argument #1 to 'strsub' (string expected, got nil)
[string "=[C]"]: ?
[string "@FastItemLevel/FastItemLevel.lua"]:261: in function <FastItemLevel/FastItemLevel.lua:246>
[string "@FastItemLevel/FastItemLevel.lua"]:376: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = nil
(*temporary) = 1
(*temporary) = 16
(*temporary) = "string expected, got nil"

**Comment by BloodDragon2580** [comment]
Test this version pls:

[FastItemLevel.zip](https://github.com/user-attachments/files/16679638/FastItemLevel.zip)

**Comment by Hollicsh** [comment]
OK. Now fine.
btw .. Previously, it showed the RIO rating.
![Screenshot_1](https://github.com/user-attachments/assets/a4ba30c1-6da3-42fe-8ab8-29cb9700504f)

**Comment by BloodDragon2580** [comment]
Rio was never planned, I accidentally included it. Unfortunately that doesn't work anymore. As soon as I have a solution for it I'll put it back in. New version is pushed to curse. Thx for your testing and your report ;).
