### ISSUE TITLE
option to hide certain things / keep only ilvl

### ISSUE THREAD

**Issue by rml9ty** [BloodDragon2580/FastItemLevel#4]
would you consider having an option to only show ilvl?

bascially I don't want to see the stuff I marked in red:
https://i.imgur.com/WD3NbK7.jpeg

that'd be great! cheers.

**Comment by BloodDragon2580** [comment]
I work on it. Give me please little time, it's xmas time 🤪

**Comment by BloodDragon2580** [comment]
New Features now Live on v6.2:
Toggle for Specialization Display:

Added a new configuration option to enable or disable the display of the player's specialization in the tooltip.
Users can control this setting via the /fil config menu.
Toggle for Mythic+ Score Display:

Introduced an option to toggle the display of the Mythic+ score.
When disabled, the total Mythic+ score will not be shown.
Dynamic Display of "Mythic+ Info" Header:

The "Mythic+ Info" header will only appear if at least one of the following is enabled:
Mythic+ Score Display
Keystone Details Display
Ensures a cleaner tooltip when Mythic+ information is irrelevant.
Configuration Changes:
Updated Configuration Menu:

Added checkboxes for the new toggles:
Show Specialization
Show Mythic+ Score
The menu updates dynamically to reflect the current configuration.
Save and Load Settings:

The user's preferences are stored and automatically loaded when the addon is initialized.
Technical Improvements:
Efficient Tooltip Updates:
Improved logic for clearing and updating tooltip lines to respect the new settings.
Enhanced Cache Management:
Tooltip customization respects cached values for smoother operation.
Benefits:
Greater flexibility to customize tooltips according to user preferences.
Cleaner and more concise tooltips by avoiding unnecessary information.
Enhanced user experience with an intuitive configuration menu.
This update ensures the addon remains lightweight, user-friendly, and tailored to individual needs!
