### ISSUE TITLE
neutral color for ilvl display

### ISSUE THREAD

**Issue by rml9ty** [BloodDragon2580/FastItemLevel#5]
ahoy again. one more very small thing.. would it be possible to have the ilvl display not change color depending on how high/low it is? just straightup one color? the color spectrum is just too wide for me, as there already is color stuff (for class) in my tooltips already. that'd be lovely!

p.s.: thanks for the other updates :-*

**Comment by BloodDragon2580** [comment]
I will look into this soon.

**Comment by BloodDragon2580** [comment]
Changelog for Version v6.3
New Feature Added:
Players can now choose whether the Item Level in the tooltip is displayed with dynamic colors.

Default: The color changes dynamically based on the item level.
Optional: Dynamic coloring can be disabled, showing the item level in white only.
Updated Configuration Menu:
A new checkbox has been added to the menu, allowing easy control of the item level color display.

Improved Localization:
Translations for the new options have been added for multiple languages, including German, English, French, Spanish, Italian, Russian, and Chinese.
