### ISSUE TITLE
"Right click for frame settings"-line in tooltip

### ISSUE THREAD

**Issue by rml9ty** [BloodDragon2580/FastItemLevel#6]
![2024-12-18 18_06_40-](https://github.com/user-attachments/assets/bccad7fc-a00e-4557-bc2b-71185b2a1e70)

I have this weird thing ("Right click for frame settings") in my tooltip. No other addons enabled. Can you replicate this?

**Comment by BloodDragon2580** [comment]
No, you can search this word in this file: https://github.com/BloodDragon2580/FastItemLevel/blob/main/FastItemLevel/FastItemLevel.lua

Thats not in it.

Sry for my Bad englisch.

**Comment by rml9ty** [comment]
I do believe its not in there, but I'm still wondering where it's coming from when FastItemLevel is the only addon I have enabled.. because that's just.. weird.

**Comment by BloodDragon2580** [comment]
Do you have weak auras?

**Comment by BloodDragon2580** [comment]
Check this: https://us.forums.blizzard.com/en/wow/t/right-click-for-frame-settings/2029960

**Comment by BloodDragon2580** [comment]
And this : https://www.reddit.com/r/wow/comments/1hgmcmf/after_todays_maintenance_all_npc_windows_have/

Its a bug from Blizzard.

**Comment by rml9ty** [comment]
you're absolutely right. didn't check beforehand. my bad, sorry for making you responsible <3

**Comment by BloodDragon2580** [comment]
no problem my friend ;)
